// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Social.Infrastructure.Persistence.Context;

#nullable disable

namespace Social.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UserManagementDbContext))]
    [Migration("20250727131206_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Social.Domain.Aggregates.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_private");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Social.Domain.Entities.BlockedUser", b =>
                {
                    b.Property<Guid>("BlockingUserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocking_user_profile_id");

                    b.Property<Guid>("BlockedUserProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("BlockingUserProfileId", "BlockedUserProfileId");

                    b.HasIndex("BlockedUserProfileId");

                    b.ToTable("blocked_user", (string)null);
                });

            modelBuilder.Entity("Social.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.Property<Guid>("FriendProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("friend_profile_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<bool>("IsSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_seen");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("UserProfileId", "FriendProfileId");

                    b.HasIndex("FriendProfileId");

                    b.ToTable("friendship", (string)null);
                });

            modelBuilder.Entity("Social.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Social.Domain.Aggregates.UserProfile", b =>
                {
                    b.OwnsOne("Social.Domain.ValueObjects.UserTag", "UserTag", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Tag")
                                .IsRequired()
                                .HasMaxLength(58)
                                .HasColumnType("character varying(58)")
                                .HasColumnName("tag");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfile");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("UserTag")
                        .IsRequired();
                });

            modelBuilder.Entity("Social.Domain.Entities.BlockedUser", b =>
                {
                    b.HasOne("Social.Domain.Aggregates.UserProfile", "BlockedUserProfile")
                        .WithMany()
                        .HasForeignKey("BlockedUserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Social.Domain.Aggregates.UserProfile", null)
                        .WithMany("BlockedUsers")
                        .HasForeignKey("BlockingUserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedUserProfile");
                });

            modelBuilder.Entity("Social.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("Social.Domain.Aggregates.UserProfile", "FriendProfile")
                        .WithMany("FriendshipsReceived")
                        .HasForeignKey("FriendProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Social.Domain.Aggregates.UserProfile", "UserProfile")
                        .WithMany("FriendshipsInitiated")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FriendProfile");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Social.Domain.Aggregates.UserProfile", b =>
                {
                    b.Navigation("BlockedUsers");

                    b.Navigation("FriendshipsInitiated");

                    b.Navigation("FriendshipsReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
